### ISSUE TITLE
rosbag 文件没有

### ISSUE THREAD

**Issue by bobd988** [Kin-Zhang/simple_ndt_slam#1]
rosbag 文件能提供吗

**Comment by Kin-Zhang** [comment]
这个可以放自己数据上用，想看看效果的话 公开数据集就行 比如kitti转一下rosbag 只需要pointcloud2就行

**Comment by bobd988** [comment]
对，我试了AdamShan 那个KAIST02-small.bag 改topic 可以运行起来。但是走一段程序就crash.

Kin ***@***.***> 于 2022年10月18日周二 下午8:50写道：

**Comment by Kin-Zhang** [comment]
我用kitti的时候没有这个问题哎 你截图一下？

**Comment by bobd988** [comment]
[image: image.png]

The attached file is the log.

**Comment by Kin-Zhang** [comment]
image上传用email的话这里没法显示，我上传了kitti的一个bag link 你可以试试
