### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by deepuav** [Kin-Zhang/simple_ndt_slam#10]
autoware.ai  无图模式可以使用ndt 定位吗？

**Comment by Kin-Zhang** [comment]
可以，运行这个node后 有一个auto_odom的topic可以当定位用

**Comment by deepuav** [comment]
autoware.ai里可以使用auto_odom 、 imu 和GSNN联合定位吗？

**Comment by Kin-Zhang** [comment]
autoware.ai 原生的我记得好像可以，这个repo已经修改了很多，对于更多auto ware的问题 建议去autoware 那边issue 较好
