### ISSUE TITLE
About the rosbag topic needed

### ISSUE THREAD

**Issue by lyysl** [Kin-Zhang/simple_ndt_slam#12]
I would like to ask do I need the topic like tf/ and robot pose in the rosbag? Or I just need the velodyne point? Or I just have 3D points message containing (x,y,z) is enough?
Thank you.

**Comment by lyysl** [comment]
I am a little bit confused, is this a repository for the paper "Real-Time Neural Dense Elevation Mapping for
Urban Terrain With Uncertainty Estimations" for dense elevation map or this is a repository for SLAM?
Thank you.

**Comment by Kin-Zhang** [comment]
A bag with have 3D points message containing (x,y,z) is enough for this package to provide pose.

**Comment by lyysl** [comment]
thank you.
