### ISSUE TITLE
not find ndt_mapping_livox.yaml

### ISSUE THREAD

**Issue by Novak88** [Kin-Zhang/simple_ndt_slam#13]
作者您好，有两个问题想请教。我运行ndt_mapping_livox.launch时，在config中没有找到指定的ndt_mapping_livox.yaml文件；另一个是我运行ndt_mapping.launch，发现在建图到后半段的时候，存在准确性问题，不知道是不是因为转弯导致，然后我修改了相关参数，缓解了建图飘的问题，但是人影出现在了结果中。
![slam1](https://github.com/user-attachments/assets/5d155b9b-d921-4e89-81ee-735246def6d6)
![slam2](https://github.com/user-attachments/assets/8c063094-8325-424e-ad79-97603a1af3ad)

**Comment by Kin-Zhang** [comment]
1. livox.lanuch 我可能忘记传了，但是看你说已经调好了 就ok，毕竟livox也有很多其他类型
2. 人影的话，你把result bag包录下来后，跟着README这里操作就能去除了：https://github.com/Kin-Zhang/simple_ndt_slam?tab=readme-ov-file#b-remove-dynamics-points-in-the-map

**Comment by Novak88** [comment]
万分感谢，我可能还需要多调下参数，建图结果似乎对参数很敏感。我昨天忘记了保存，今天再试了几次，就得不到跟之前类似的效果了
