### ISSUE TITLE
error:Duration is out of dual 32-bit range

### ISSUE THREAD

**Issue by Urleaves** [Kin-Zhang/simple_ndt_slam#14]
作者你好！我使用 simple-ndt 进行建图时，程序崩溃并出现了 Duration is out of dual 32-bit range 错误。 我推测代码遇到了时间戳超出 32 位整数范围的问题。
我使用的是实际的激光雷达，所以删掉了ndt_mapping.launch的rosbag相关的程序，然后出现了如下的报错。而且在rviz上只出现了应该是一帧的点云图。不知道你是否有遇到过类似的问题，期待您的回复！
![d45a8018eb2a1534854b83ce6de1700](https://github.com/user-attachments/assets/2a0d125b-8749-4dda-a6c4-736be4b8a0fc)

**Comment by Kin-Zhang** [comment]
没有哎，我也跑过实际的机器人上的，没有错误出现

如果可以的话 可以先试着把bag录一下，看一下bag跑也有这个error嘛？

**Comment by Urleaves** [comment]
好的好的，我再顺便问一下，在实际机器人上跑时，对激光雷达的数据格式和频率有没有什么要求？我担心是我直接把点云放上去，没有做什么处理，这个有关系吗？

**Comment by Urleaves** [comment]
已经解决啦，应该是我机器上时钟不对的原因，现在时钟对了之后就好了。十分感谢！
