### ISSUE TITLE
"/ndt_map"输出的只是激光雷达扫描的数据

### ISSUE THREAD

**Issue by dbw100** [Kin-Zhang/simple_ndt_slam#5]
您好，请问一下，为什么我运行ndt_mapping之后, "/ndt_map"输出的只是雷达扫描的数据。

**Comment by dbw100** [comment]
![捕获1](https://user-images.githubusercontent.com/57590483/234592699-39ccc5fc-4136-4f93-8364-66d344d4e3b9.JPG)
感谢您的回复，好像是有里程计数据的，但是"/ndt_map"这个话题好像输出的是雷达的原始数据，不是建图的结果，我是在自己的电脑上编译的。

**Comment by Kin-Zhang** [comment]
奥，里程计数据有的话 你看一下config file，这里应该是-1，不过我记得rviz无论如何都会显示才对... 
方便的话 你录个视频 开头看一下launch和config，然后launch一下 我看一下终端输出和rviz？
```
debug_print: true  # will republish point with current timestamp
# setting -1 mean it will output the whole ndt map ===> FOR THE WHOLE MAP
# setting 10 mean 10*frame_point_num will be saved ===> FOR FAST LOC
save_frame_point: -1
```

**Comment by Kin-Zhang** [comment]
Ha, 我知道了 因为效率原因 我没有把全部的ndt_map pub出来【影响实时性】

---

你直接打开 这个repo下的rviz文件就能看到了：https://github.com/Kin-Zhang/simple_ndt_slam/blob/master/lidar_localizer/rviz/ndt_mapping.rviz

或者是delay time 设到很大很大 也ok

---

具体可以在launch file里加：
```
<node type="rviz" name="rviz_mapper" pkg="rviz" args="-d $(find lidar_localizer)/rviz/ndt_mapping.rviz" />
```

**Comment by dbw100** [comment]
哦哦，非常感谢大佬的解答，我看rviz的配置已经写进了launch文件中，但是在运行launch文件时，rviz会显示一下，然后立即闪退，所以我才新开了一个rviz的窗口。不知道rviz闪退是这个问题。

https://user-images.githubusercontent.com/57590483/234621775-04caa003-a36a-4e99-9230-a8e1c23151e6.mp4

还有就是地图保存也出现了问题
![捕获4](https://user-images.githubusercontent.com/57590483/234621912-a5110ff3-e700-4d51-b3e7-6fea5a98a28d.JPG)

**Comment by dbw100** [comment]
https://user-images.githubusercontent.com/57590483/234784893-b9eb9e57-3f06-4ade-bb84-d2e6fb5ced11.mp4
您好，这是录制的闪退情况，这个rviz闪退是间断发生的，有时候是正常的。现在点云地图可以正常保存，谢谢。还有就是在rviz中实时显示建图结果要在哪里进行修改呢？

**Comment by Kin-Zhang** [comment]
![image](https://user-images.githubusercontent.com/35365764/234980025-9ff8159c-9bed-4cb2-851f-9b94de2cf40f.png)

**Comment by dbw100** [comment]
好的，非常感谢！
