### ISSUE TITLE
开学前几个疑问

### ISSUE THREAD

**Issue by deepuav** [Kin-Zhang/simple_ndt_slam#8]
1、这个3D定位还是2d定位？
2、这个需要提前预置地图吗？
3、那个输入的odom topic是不是GNSS？

**Comment by Kin-Zhang** [comment]
1. 3d 实时建议与定位
2. 不需要
3. 不是 只是一个名字而已，把雷达点topic name给对就可以了

**Comment by deepuav** [comment]
1、autoware，也可以使用这个ndt slam 定位，不需要预置高精地图。对吧？
2、autoware的planner避障是3D的还是2D的？
3、autoware与车辆的接口，应加学习哪部分资料啊？我们的载具是离地面10到30米飞行的车辆

**Comment by deepuav** [comment]
传感感也打算使用速腾M1 激光雷达

**Comment by Kin-Zhang** [comment]
1、是的 不需要（不过如果要做planner autoware 内置有些是需要自己绘制高精地图的 建议参考autoware文档
2、看用哪个planner 模块了 同上建议
3、not sure
