### ISSUE TITLE
Dynamic Object Removal

### ISSUE THREAD

**Issue by arwinder-jaspal** [Kin-Zhang/simple_ndt_slam#9]
When I tried the post-processing steps to remove dynamic obstacles, it generates one pcd fle for each point cloud msg. How do i generate only one PCD file similar to the output of simple_ndt?

**Comment by Kin-Zhang** [comment]
Hi,
check here: https://github.com/Kin-Zhang/simple_ndt_slam/blob/master/tools/src/extract_pcdFbag_tf.cpp

```
cd tools
cmake -B build && cmake --build build
# format
./bag2pcd_tf <rosbag_path> <save_pcd_folder> <pc2_topic_name> <world_or_map_frame_id>
# example
./bag2pcd_tf /home/kin/pointclouds.bag /home/kin/Tmp /camera/rgb/points world
```
